### ISSUE TITLE
decrease minimum dimensions below 512px

### ISSUE THREAD

**Issue by dickhardt** [Stability-AI/REST-API#3]
For landscape images, 512px is larger than needed for some use cases - eg. generating a banner for an online profile.

The current API docs state 192 - 256 is minimal recommended dimension. 

Perhaps allow any height and width dimensions that are divisible by 64 and  height X width are between 262k and 1M?

**Comment by todd-elvers** [comment]
This is something we'll add to the v1beta I'm currently working on.  Thank you for the suggestion!

**Comment by todd-elvers** [comment]
We're changing `v1beta` so that the minimum height/width dimension is `128` with no upper bound on the dimension size.  Instead we'll verify that the pixel count of the image is between 262K and 1MP.  This allows for dimensions like `192x3072`:

![wide](https://user-images.githubusercontent.com/5025641/211872421-5d17aff5-1c12-4d9b-a18a-873d339d3b47.png)

**Comment by todd-elvers** [comment]
This has been deployed to production!
